on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml
name: Semgrep
jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
    - uses: actions/checkout@v4
    - name: Setup java
      uses: actions/setup-java@v4.5.0
      with:
        distribution: 'temurin'
        java-version: 21
    - name: build deptree
      run: |
        ./mvnw clean package
        ./mvnw dependency:tree -DoutputFile=maven_dep_tree.txt
    - run: semgrep ci
