on:
  workflow_dispatch: {}
  pull_request: {}
  push:
    branches:
    - main
    - master
    paths:
    - .github/workflows/semgrep.yml

env:
  # https://github.com/actions/virtual-environments/issues/1499
  MAVEN_CLI_OPTS: '-ntp --batch-mode --errors --fail-at-end --show-version -Dmaven.wagon.httpconnectionManager.ttlSeconds=60 -Dmaven.wagon.http.retryHandler.count=3 -Dstyle.color=always'
  CT_BUILD_ID: '${{ github.run_id }}'
  KEYCLOAK_VERSION: 26.1.0
  KEYCLOAK_CLIENT_VERSION: 26.0.4
name: Semgrep
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup java
        uses: actions/setup-java@v4.5.0
        with:
          distribution: 'temurin'
          java-version: 21

      - uses: actions/cache@v4.2.0
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ matrix.env.KEYCLOAK_VERSION }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-${{ matrix.env.KEYCLOAK_VERSION }}
      - name: Build & Test
        run: |
          ./mvnw ${MAVEN_CLI_OPTS} -Dkeycloak.version=${{ env.KEYCLOAK_VERSION }} -Dkeycloak.client.version=${{ env.KEYCLOAK_CLIENT_VERSION }} clean verify
          ./mvnw dependency:tree -DoutputFile=maven_dep_tree.txt
      - name: semgrep scan
        run: |
          docker run -rm -e "SEMGREP_APP_TOKEN=${{ secrets.SEMGREP_APP_TOKEN }}" -v "$(pwd)":/src semgrep/semgrep
